spring:
  main:
    allow-bean-definition-overriding: true
  #
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/discipline?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: discipline
    password: keepdiscipline
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: HikariCP
      read-only: false
      connection-test-query: SELECT 1
  # spring data jpa 설정
  jpa:
    open-in-view: false
    #만들어진 sql 보여줌
    show-sql: false
    #db 초기화 전략. 기존 테이블 삭제 후 생성
    hibernate:
      ddl-auto: none
  # flyway 설정
  flyway:
    url: jdbc:mysql://127.0.0.1:3306/discipline?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    user: discipline
    password: keepdiscipline
    enabled: true
    baseline-on-migrate: true
  logging:
    lelve:
      root: DEBUG